# Generated by Django 4.0.4 on 2022-06-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gikians',
            fields=[
                ('reg_no', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('hash', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('faculty', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=40)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor_best_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_courses', models.CharField(max_length=40)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians')),
            ],
        ),
        migrations.CreateModel(
            name='Mentees_weak_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weak_courses', models.CharField(max_length=40)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians')),
            ],
        ),
        migrations.CreateModel(
            name='Mentees_of_mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_ids', to='main_web.gikians')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians')),
            ],
        ),
        migrations.CreateModel(
            name='Mentees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('mentor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_ids', to='main_web.gikians')),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_no_is', to='main_web.gikians')),
            ],
        ),
        migrations.CreateModel(
            name='Mentee_interests',
            fields=[
                ('interests', models.CharField(max_length=40)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians')),
            ],
        ),
        migrations.AddField(
            model_name='gikians',
            name='uni_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.university'),
        ),
        migrations.CreateModel(
            name='Giki_teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.CharField(max_length=30)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians')),
            ],
        ),
        migrations.CreateModel(
            name='Giki_socities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socities', models.CharField(max_length=30)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_web.gikians')),
            ],
        ),
    ]
